# Generated by Django 5.0.6 on 2024-06-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodrecipes',
            old_name='needed_ings_amount',
            new_name='needed_ings',
        ),
    ]
